/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'
import { Route as AccountSignInRouteImport } from './routes/account/sign-in'
import { Route as AccountRegisterRouteImport } from './routes/account/register'

const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSignInRoute = AccountSignInRouteImport.update({
  id: '/account/sign-in',
  path: '/account/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/account/register': typeof AccountRegisterRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/': typeof homeIndexRoute
  '/about': typeof AboutIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesByTo {
  '/account/register': typeof AccountRegisterRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/': typeof homeIndexRoute
  '/about': typeof AboutIndexRoute
  '/search': typeof SearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/account/register': typeof AccountRegisterRoute
  '/account/sign-in': typeof AccountSignInRoute
  '/(home)/': typeof homeIndexRoute
  '/about/': typeof AboutIndexRoute
  '/search/': typeof SearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/account/register'
    | '/account/sign-in'
    | '/'
    | '/about'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/account/register' | '/account/sign-in' | '/' | '/about' | '/search'
  id:
    | '__root__'
    | '/account/register'
    | '/account/sign-in'
    | '/(home)/'
    | '/about/'
    | '/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountSignInRoute: typeof AccountSignInRoute
  homeIndexRoute: typeof homeIndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/sign-in': {
      id: '/account/sign-in'
      path: '/account/sign-in'
      fullPath: '/account/sign-in'
      preLoaderRoute: typeof AccountSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AccountRegisterRoute: AccountRegisterRoute,
  AccountSignInRoute: AccountSignInRoute,
  homeIndexRoute: homeIndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
